package org.mdt.ui.screens.editor.model

import org.mdt.core.ui.Rect
import org.mdt.core.ui.graphics.Color
import org.mdt.ui.theme.StudioIcons

/**
 * ## EditorMode
 *
 * Workspace mode determining active sidebar tabs, viewport canvas renderers,
 * and top-level studio tool configurations.
 *
 * See: docs/design-system/design_system_en.md
 */
enum class EditorMode(val title: String, val iconUrl: String) {
    SCENE("Scene", StudioIcons.SCENE),
    COMPONENTS("Components", StudioIcons.COMPONENTS),
    ASSETS("Assets", StudioIcons.IMAGE),
    I18N("i18n", StudioIcons.I18N),
    SETTINGS("Settings", StudioIcons.SETTINGS);

    val displayName: String get() = title
}

/**
 * ## GizmoHandle
 *
 * 8 perimeter interactive resize handles and body drag handle for 2D transform manipulation.
 *
 * See: docs/design-system/design_system_en.md
 */
enum class GizmoHandle {
    NONE, BODY,
    TOP_LEFT, TOP_CENTER, TOP_RIGHT,
    LEFT_CENTER, RIGHT_CENTER,
    BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT;

    companion object {
        /**
         * Hit-tests pointer coordinates against the 8 perimeter handles of a node's bounding rectangle.
         */
        fun testHit(pointerX: Float, pointerY: Float, bounds: Rect, hitTolerance: Float = 10f): GizmoHandle {
            val boundX = bounds.x
            val boundY = bounds.y
            val boundWidth = bounds.width
            val boundHeight = bounds.height

            fun hit(handleX: Float, handleY: Float): Boolean =
                pointerX in (handleX - hitTolerance)..(handleX + hitTolerance) &&
                pointerY in (handleY - hitTolerance)..(handleY + hitTolerance)

            return when {
                hit(boundX, boundY + boundHeight) -> TOP_LEFT
                hit(boundX + boundWidth * 0.5f, boundY + boundHeight) -> TOP_CENTER
                hit(boundX + boundWidth, boundY + boundHeight) -> TOP_RIGHT
                hit(boundX, boundY + boundHeight * 0.5f) -> LEFT_CENTER
                hit(boundX + boundWidth, boundY + boundHeight * 0.5f) -> RIGHT_CENTER
                hit(boundX, boundY) -> BOTTOM_LEFT
                hit(boundX + boundWidth * 0.5f, boundY) -> BOTTOM_CENTER
                hit(boundX + boundWidth, boundY) -> BOTTOM_RIGHT
                else -> NONE
            }
        }
    }
}

/**
 * ## TreeItemData
 *
 * Immutable presentation model representing a single row in the Layer Tree hierarchy.
 * Generated by traversing the live In-Memory Virtual Node Scene Graph.
 *
 * See: docs/design-system/design_system_en.md
 */
data class TreeItemData(
    val id: String,
    val name: String,
    val type: String,
    val iconUrl: String,
    val iconTint: Color = Color.White,
    val depth: Int = 0,
    val isExpandable: Boolean = false,
    val isExpanded: Boolean = false
)
