package org.mdt.ui.screens.editor.model

import org.mdt.core.ui.graphics.Color

/**
 * ## TreeItemData
 *
 * Immutable presentation model representing a single row in the Layer Tree hierarchy.
 * Generated by traversing the live In-Memory Virtual Node Scene Graph.
 *
 * See: docs/design-system/design_system_en.md
 */
data class TreeItemData(
    val id: String,
    val name: String,
    val type: String,
    val iconUrl: String,
    val iconTint: Color = Color.White,
    val depth: Int = 0,
    val isExpandable: Boolean = false,
    val isExpanded: Boolean = false
)
