package org.mdt.core.engine.i18n

/**
 * ## LocaleMetadata
 *
 * Descriptive metadata for a supported language/locale in the Studio.
 *
 * See: docs/core-subsystems/core_subsystems_en.md
 */
data class LocaleMetadata(
    val code: String,
    val displayName: String,
    val nativeName: String,
    val iconFlag: String = ""
) {
    companion object {
        val DEFAULT_LOCALES = listOf(
            LocaleMetadata("en", "English", "English"),
            LocaleMetadata("vi", "Vietnamese", "Tiếng Việt"),
            LocaleMetadata("ja", "Japanese", "日本語"),
            LocaleMetadata("ru", "Russian", "Русский"),
            LocaleMetadata("zh_CN", "Simplified Chinese", "简体中文"),
            LocaleMetadata("ko", "Korean", "한국어"),
            LocaleMetadata("fr", "French", "Français"),
            LocaleMetadata("de", "German", "Deutsch"),
            LocaleMetadata("es", "Spanish", "Español"),
            LocaleMetadata("uk", "Ukrainian", "Українська")
        )
    }
}

/**
 * ## MissingKeyEntry
 *
 * Diagnostic record representing a translation key that was queried at runtime
 * but was missing in the active locale bundle.
 */
data class MissingKeyEntry(
    val key: String,
    val locale: String,
    val firstSeenMillis: Long = System.currentTimeMillis(),
    val sampleParams: List<String> = emptyList()
)

/**
 * ## LocaleStats
 *
 * Summary statistics representing translation completion progress for a specific locale.
 */
data class LocaleStats(
    val locale: String,
    val totalKeys: Int,
    val translatedKeys: Int,
    val missingKeys: Int,
    val coverageRatio: Float
) {
    val coveragePercent: Int
        get() = (coverageRatio * 100f).toInt()
}

/**
 * ## AiTranslationEntry
 *
 * Key-value pair proposed for or generated by AI translation assistance.
 */
data class AiTranslationEntry(
    val key: String,
    val sourceEnglish: String,
    var proposedTranslation: String = "",
    var isSelected: Boolean = true
)
